//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MovieReviews", "fk_reviews_movies", "movies", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(linq_entityframework_part1.Movie), "reviews", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(linq_entityframework_part1.Review))]

// Original file name:
// Generation date: 12/2/2008 2:17:08 PM
namespace linq_entityframework_part1
{
    
    /// <summary>
    /// There are no comments for MovieReviewEntities in the schema.
    /// </summary>
    public partial class MovieReviewEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MovieReviewEntities object using the connection string found in the 'MovieReviewEntities' section of the application configuration file.
        /// </summary>
        public MovieReviewEntities() : 
                base("name=MovieReviewEntities", "MovieReviewEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MovieReviewEntities object.
        /// </summary>
        public MovieReviewEntities(string connectionString) : 
                base(connectionString, "MovieReviewEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MovieReviewEntities object.
        /// </summary>
        public MovieReviewEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MovieReviewEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Movies in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Movie> Movies
        {
            get
            {
                if ((this._Movies == null))
                {
                    this._Movies = base.CreateQuery<Movie>("[Movies]");
                }
                return this._Movies;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Movie> _Movies;
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Review> Reviews
        {
            get
            {
                if ((this._Reviews == null))
                {
                    this._Reviews = base.CreateQuery<Review>("[Reviews]");
                }
                return this._Reviews;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Review> _Reviews;
        /// <summary>
        /// There are no comments for Movies in the schema.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        public void AddToReviews(Review review)
        {
            base.AddObject("Reviews", review);
        }
        /// <summary>
        /// There are no comments for MovieReviews.GetHishestRankedMovies in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectResult<Movie> GetHishestRankedMovies(global::System.Nullable<global::System.DateTime> sinceDate)
        {
            global::System.Data.Objects.ObjectParameter sinceDateParameter;
            if (sinceDate.HasValue)
            {
                sinceDateParameter = new global::System.Data.Objects.ObjectParameter("SinceDate", sinceDate);
            }
            else
            {
                sinceDateParameter = new global::System.Data.Objects.ObjectParameter("SinceDate", typeof(global::System.DateTime));
            }
            return base.ExecuteFunction<Movie>("GetHishestRankedMovies", sinceDateParameter);
        }
    }
    /// <summary>
    /// There are no comments for MovieReviews.Movie in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MovieReviews", Name="Movie")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Movie : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="title">Initial value of Title.</param>
        /// <param name="releaseDate">Initial value of ReleaseDate.</param>
        public static Movie CreateMovie(int id, string title, global::System.DateTime releaseDate)
        {
            Movie movie = new Movie();
            movie.ID = id;
            movie.Title = title;
            movie.ReleaseDate = releaseDate;
            return movie;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Title in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
        /// <summary>
        /// There are no comments for Property ReleaseDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime ReleaseDate
        {
            get
            {
                return this._ReleaseDate;
            }
            set
            {
                this.OnReleaseDateChanging(value);
                this.ReportPropertyChanging("ReleaseDate");
                this._ReleaseDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ReleaseDate");
                this.OnReleaseDateChanged();
            }
        }
        private global::System.DateTime _ReleaseDate;
        partial void OnReleaseDateChanging(global::System.DateTime value);
        partial void OnReleaseDateChanged();
        /// <summary>
        /// There are no comments for Reviews in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MovieReviews", "fk_reviews_movies", "reviews")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Review> Reviews
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Review>("MovieReviews.fk_reviews_movies", "reviews");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Review>("MovieReviews.fk_reviews_movies", "reviews", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MovieReviews.Review in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MovieReviews", Name="Review")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Review : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Review object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="summary">Initial value of summary.</param>
        /// <param name="rating">Initial value of Rating.</param>
        /// <param name="review1">Initial value of review.</param>
        public static Review CreateReview(int id, string summary, int rating, string review1)
        {
            Review review = new Review();
            review.ID = id;
            review.summary = summary;
            review.Rating = rating;
            review.review = review1;
            return review;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property summary in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string summary
        {
            get
            {
                return this._summary;
            }
            set
            {
                this.OnsummaryChanging(value);
                this.ReportPropertyChanging("summary");
                this._summary = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("summary");
                this.OnsummaryChanged();
            }
        }
        private string _summary;
        partial void OnsummaryChanging(string value);
        partial void OnsummaryChanged();
        /// <summary>
        /// There are no comments for Property Rating in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this._Rating;
            }
            set
            {
                this.OnRatingChanging(value);
                this.ReportPropertyChanging("Rating");
                this._Rating = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Rating");
                this.OnRatingChanged();
            }
        }
        private int _Rating;
        partial void OnRatingChanging(int value);
        partial void OnRatingChanged();
        /// <summary>
        /// There are no comments for Property review in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string review
        {
            get
            {
                return this._review;
            }
            set
            {
                this.OnreviewChanging(value);
                this.ReportPropertyChanging("review");
                this._review = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("review");
                this.OnreviewChanged();
            }
        }
        private string _review;
        partial void OnreviewChanging(string value);
        partial void OnreviewChanged();
        /// <summary>
        /// There are no comments for Property reviewer in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string reviewer
        {
            get
            {
                return this._reviewer;
            }
            set
            {
                this.OnreviewerChanging(value);
                this.ReportPropertyChanging("reviewer");
                this._reviewer = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("reviewer");
                this.OnreviewerChanged();
            }
        }
        private string _reviewer;
        partial void OnreviewerChanging(string value);
        partial void OnreviewerChanged();
        /// <summary>
        /// There are no comments for movies in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MovieReviews", "fk_reviews_movies", "movies")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Movie movies
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviews.fk_reviews_movies", "movies").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviews.fk_reviews_movies", "movies").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for movies in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Movie> moviesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Movie>("MovieReviews.fk_reviews_movies", "movies");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Movie>("MovieReviews.fk_reviews_movies", "movies", value);
                }
            }
        }
    }
}
